name: Kalender aktualisieren

on:
  schedule:
    - cron: '0 4 * * *'  # Täglich um 4 Uhr
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: pip install icalendar requests

      - name: Kalender bereinigen
        run: python clean_calendar.py

      - name: Output pushen
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/rlp_kalender_cleaned.ics
          git commit -m "Update Kalender"
          git push
